(function(global){
 class Graph{
  constructor(canvas,opts={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.scale=opts.scale||32;this.offsetX=0;this.offsetY=0;this.curves=[];this.parametrics=[];this.points=[];this.asymptotes=[];this.onDraw=null;this.onPointer=null;this.dragging=false;this._bind();this.resize();}
  _bind(){const c=this.canvas;let last=null;c.addEventListener('mousedown',e=>{if(this._onPointDrag&&this._onPointDrag(e,'start'))return;this.dragging=true;last={x:e.clientX,y:e.clientY};});window.addEventListener('mousemove',e=>{const r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;if(this.onPointer)this.onPointer(this.screenToWorld(px,py),e);if(this._onPointDrag&&this._onPointDrag(e,'move'))return;if(!this.dragging)return;this.offsetX+=(e.clientX-last.x)/this.scale;this.offsetY-=(e.clientY-last.y)/this.scale;last={x:e.clientX,y:e.clientY};this.draw();});window.addEventListener('mouseup',e=>{this.dragging=false;if(this._onPointDrag)this._onPointDrag(e,'end');});c.addEventListener('wheel',e=>{e.preventDefault();const before=this.screenToWorld(e.offsetX,e.offsetY),factor=e.deltaY<0?1.1:.9;this.scale=Math.max(4,Math.min(500,this.scale*factor));const after=this.screenToWorld(e.offsetX,e.offsetY);this.offsetX+=before.x-after.x;this.offsetY+=before.y-after.y;this.draw();},{passive:false});window.addEventListener('resize',()=>this.resize());}
  resize(){const r=this.canvas.getBoundingClientRect(),d=window.devicePixelRatio||1;this.canvas.width=Math.max(1,r.width*d);this.canvas.height=Math.max(1,r.height*d);this.ctx.setTransform(d,0,0,d,0,0);this.w=r.width;this.h=r.height;this.originX=this.w/2;this.originY=this.h/2;this.draw();}
  worldToScreen(x,y){return{x:this.originX+(x+this.offsetX)*this.scale,y:this.originY-(y+this.offsetY)*this.scale};}
  screenToWorld(px,py){return{x:(px-this.originX)/this.scale-this.offsetX,y:-(py-this.originY)/this.scale-this.offsetY};}
  reset(){this.offsetX=0;this.offsetY=0;this.scale=32;this.draw();}
  fitToContent(){let max=0;const scan=(x,y)=>{if(Number.isFinite(x)&&Number.isFinite(y))max=Math.max(max,Math.abs(x),Math.abs(y));};for(const p of this.parametrics){for(let i=0;i<=260;i++){const t=p.tMin+(p.tMax-p.tMin)*i/260;scan(p.fnx(t),p.fny(t));}}for(const c of this.curves){for(let i=0;i<=260;i++){const x=-10+20*i/260;scan(x,c.fn(x));}}if(max>0){this.offsetX=0;this.offsetY=0;this.scale=Math.max(8,Math.min(85,Math.min(this.w,this.h)/(2*max*1.18)));}this.draw();}
  clearCurves(){this.curves=[]} addCurve(fn,color='#5dd8ff',width=2.7){this.curves.push({fn,color,width})}
  clearParametrics(){this.parametrics=[]} addParametric(fnx,fny,tMin,tMax,color='#8a5cff',width=2.7,close=false){this.parametrics.push({fnx,fny,tMin,tMax,color,width,close})}
  clearPoints(){this.points=[]} addPoint(x,y,color='#ff2fba',radius=5,label=''){this.points.push({x,y,color,radius,label})}
  draw(){const{ctx,w,h}=this;ctx.clearRect(0,0,w,h);this._grid();this._axes();this._asymptotes();for(const c of this.curves)this._function(c);for(const p of this.parametrics)this._parametric(p);for(const p of this.points)this._point(p);if(this.onDraw)this.onDraw(this);}
  _nice(){const raw=65/this.scale,p=Math.pow(10,Math.floor(Math.log10(raw))),n=raw/p;return(n<1.5?1:n<3.5?2:n<7.5?5:10)*p}
  _grid(){const{ctx,w,h}=this,step=this._nice(),cs=getComputedStyle(document.documentElement);ctx.strokeStyle=cs.getPropertyValue('--grid-line')||'rgba(90,150,230,.12)';ctx.lineWidth=1;const l=this.screenToWorld(0,0).x,r=this.screenToWorld(w,0).x,t=this.screenToWorld(0,0).y,b=this.screenToWorld(0,h).y;ctx.beginPath();for(let x=Math.floor(l/step)*step;x<=r;x+=step){let s=this.worldToScreen(x,0);ctx.moveTo(s.x,0);ctx.lineTo(s.x,h)}for(let y=Math.floor(b/step)*step;y<=t;y+=step){let s=this.worldToScreen(0,y);ctx.moveTo(0,s.y);ctx.lineTo(w,s.y)}ctx.stroke();ctx.fillStyle=cs.getPropertyValue('--muted')||'#8094b4';ctx.font='10px JetBrains Mono,monospace';for(let x=Math.floor(l/step)*step;x<=r;x+=step){let s=this.worldToScreen(x,0);if(s.x>0&&s.x<w-15&&Math.abs(x)>1e-10)ctx.fillText(this._fmt(x),s.x+3,this.worldToScreen(0,0).y+13)}for(let y=Math.floor(b/step)*step;y<=t;y+=step){let s=this.worldToScreen(0,y);if(s.y>12&&s.y<h-2&&Math.abs(y)>1e-10)ctx.fillText(this._fmt(y),this.worldToScreen(0,0).x+5,s.y-3)}}
  _fmt(v){const r=Math.round(v*1000)/1000;return Math.abs(r)<1e-9?'0':String(r)}
  _axes(){const{ctx,w,h}=this,cs=getComputedStyle(document.documentElement);const p=this.worldToScreen(0,0);ctx.strokeStyle=cs.getPropertyValue('--axis-color')||'#7890b0';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(p.x,0);ctx.lineTo(p.x,h);ctx.moveTo(0,p.y);ctx.lineTo(w,p.y);ctx.stroke();ctx.fillStyle=cs.getPropertyValue('--cyan')||'#5dd8ff';ctx.font='700 10px JetBrains Mono';ctx.fillText('y',p.x+6,12);ctx.fillText('x',w-13,p.y-7)}
  _asymptotes(){if(!this.asymptotes.length)return;const{ctx,h}=this;ctx.save();ctx.strokeStyle='#ff5577';ctx.setLineDash([5,6]);for(const a of this.asymptotes){const p=this.worldToScreen(a,0);ctx.beginPath();ctx.moveTo(p.x,0);ctx.lineTo(p.x,h);ctx.stroke()}ctx.restore()}
  _function(c){const{ctx,w,h}=this;ctx.save();ctx.shadowBlur=12;ctx.shadowColor=c.color;ctx.strokeStyle=c.color;ctx.lineWidth=c.width;ctx.lineJoin='round';ctx.beginPath();let started=false,prevY=null;for(let px=0;px<=w;px++){const x=this.screenToWorld(px,0).x,y=c.fn(x);if(!Number.isFinite(y)){started=false;prevY=null;continue}const s=this.worldToScreen(x,y);if(prevY!==null&&Math.abs(s.y-prevY)>h*1.3)started=false;if(!started){ctx.moveTo(s.x,s.y);started=true}else ctx.lineTo(s.x,s.y);prevY=s.y}ctx.stroke();ctx.restore()}
  _parametric(p){const{ctx}=this;ctx.save();ctx.shadowBlur=12;ctx.shadowColor=p.color;ctx.strokeStyle=p.color;ctx.lineWidth=p.width;ctx.lineJoin='round';ctx.beginPath();let started=false,prev=null;const steps=1200;for(let i=0;i<=steps;i++){const t=p.tMin+(p.tMax-p.tMin)*i/steps,x=p.fnx(t),y=p.fny(t);if(!Number.isFinite(x)||!Number.isFinite(y)){started=false;prev=null;continue}const s=this.worldToScreen(x,y);if(prev&&Math.hypot(s.x-prev.x,s.y-prev.y)>Math.max(this.w,this.h)*.5)started=false;if(!started){ctx.moveTo(s.x,s.y);started=true}else ctx.lineTo(s.x,s.y);prev=s}if(p.close)ctx.closePath();ctx.stroke();ctx.restore()}
  _point(p){const{ctx}=this,s=this.worldToScreen(p.x,p.y);ctx.fillStyle=p.color;ctx.shadowBlur=12;ctx.shadowColor=p.color;ctx.beginPath();ctx.arc(s.x,s.y,p.radius,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.stroke();if(p.label){ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--text');ctx.font='600 10px Inter';ctx.fillText(p.label,s.x+8,s.y-8)}}
 }
 global.Graph=Graph;
})(window);
